
// this file is automatically generated by git.version.ts script
export const versions = {
  version: '0.0.2-alpha2',
<<<<<<< HEAD
  revision: 'eef86af',
=======
  revision: '22a9325',
>>>>>>> 1b95b70270417d2e3aa753fdd4e5d3ac73bf2869
  branch: 'master'
};